package org.scalatheagorist.freeflowfeedszio.publisher

import org.scalatheagorist.freeflowfeedszio.models.Article
import org.scalatheagorist.freeflowfeedszio.models.HtmlResponse
import org.scalatheagorist.freeflowfeedszio.models.RSSFeed
import zio.Scope
import zio._
import zio.test.Spec
import zio.test.TestEnvironment
import zio.test.ZIOSpecDefault
import zio.test.assertTrue

object MisesDESpec extends ZIOSpecDefault {
  override def spec: Spec[TestEnvironment with Scope, Any] = suite("MisesDE") {
    test("toRSSFeedStream must convert html code to a RSSFeed") {
      for {
        htmlResp <- ZIO.succeed(HtmlResponse(Publisher.MISESDE, htmlResponse))
        build    <- MisesDE.toRSSFeedStream(htmlResp).runLast
      } yield assertTrue(build.contains(RSSFeed(
        author = "Rainer Zitelmann",
        article = Article(
          title = "Jung, rebellisch, kapitalistisch: Kennen Sie schon die Anti-Klima-Kleber?",
          link = "https://www.misesde.org/2023/08/jung-rebellisch-kapitalistisch-kennen-sie-schon-die-anti-klima-kleber/"
        ),
        publisher = Publisher.MISESDE,
        lang = Lang.DE
      )))
    }
  }

  private def htmlResponse: String = {
    s"""
       |<div class="pt-cv-view pt-cv-grid pt-cv-colsys pt-cv-same-height pt-cv-post-border pt-cv-content-hover pt-cv-clickable pt-cv-force-mask pt-cv-overlay-bottom pt-cv-pgregular" id="pt-cv-view-dacd42bydp"><div data-id="pt-cv-page-1" class="pt-cv-page" data-cvc="2" data-cvct="2" data-cvcm="1"><div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="31020"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 57.8667px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg" srcset="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>LvMID</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-10-13T07:40:18+02:00">13. Oktober 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/10/die-heldenreise-des-buergers-vom-untertan-zum-souveraen/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/10/20231011-adobestock_129103370-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/10/20231011-adobestock_129103370-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Die Heldenreise des Bürgers. Vom Untertan zum Souverän" decoding="async" fetchpriority="high" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/10/die-heldenreise-des-buergers-vom-untertan-zum-souveraen/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Die Heldenreise des Bürgers. Vom Untertan zum Souverän</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="31016"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 57.8667px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2012/12/Dr_Eduard_Braun.jpg" srcset="https://www.misesde.org/wp-content/uploads/2012/12/Dr_Eduard_Braun.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Eduard Braun</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-10-11T08:27:01+02:00">11. Oktober 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/10/podcast-deutschland-als-versuchskaninchen-eines-sozial-oekologischen-experiments/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/07/20230720-adobestock_105211200-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/07/20230720-adobestock_105211200-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="PODCAST: Deutschland als Versuchskaninchen eines sozial-ökologischen Experiments" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/10/podcast-deutschland-als-versuchskaninchen-eines-sozial-oekologischen-experiments/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">PODCAST: Deutschland als Versuchskaninchen eines sozial-ökologischen Experiments</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30992"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 55.5333px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2013/10/George_Reisman2.jpg" srcset="https://www.misesde.org/wp-content/uploads/2013/10/George_Reisman2.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>George Reisman</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-10-10T08:32:30+02:00">10. Oktober 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/10/zu-ehren-ludwig-von-mises-50-todestag/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/10/20231008-mises-520x360.jpg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/10/20231008-mises-520x360.jpg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Zu Ehren Ludwig von Mises | 50. Todestag" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 39.6px;"><a href="https://www.misesde.org/2023/10/zu-ehren-ludwig-von-mises-50-todestag/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Zu Ehren Ludwig von Mises | 50. Todestag</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30983"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 55.5333px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2022/12/20221207-johanna_u_manuel.png" srcset="https://www.misesde.org/wp-content/uploads/2022/12/20221207-johanna_u_manuel.png 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Johanna &amp; Manuel</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-10-04T09:53:51+02:00">4. Oktober 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/10/kuendigt-den-faustischen-fiatgeld-pakt-mises-momente-11/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/10/mm11_thumbnail_landscape-520x360.png&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/10/mm11_thumbnail_landscape-520x360.png" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Kündigt den faustischen Fiatgeld Pakt! | MISES Momente #11" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 39.6px;"><a href="https://www.misesde.org/2023/10/kuendigt-den-faustischen-fiatgeld-pakt-mises-momente-11/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Kündigt den faustischen Fiatgeld Pakt! | MISES Momente #11</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30962"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 51.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg" srcset="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>LvMID</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-10-02T07:34:16+02:00">2. Oktober 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/10/mises-monatsmagazin-die-beitraege-im-september-2023/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/03/20230328-adobestock_56479643-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/03/20230328-adobestock_56479643-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="MISES Monatsmagazin - Die Beiträge im September 2023" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 39.6px;"><a href="https://www.misesde.org/2023/10/mises-monatsmagazin-die-beitraege-im-september-2023/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">MISES Monatsmagazin – Die Beiträge im September 2023</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30944"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 51.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2023/09/20230926-foto_thorsten_andreas-scaled.jpg" srcset="https://www.misesde.org/wp-content/uploads/2023/09/20230926-foto_thorsten_andreas-scaled.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Thorsten Polleit &amp; Andreas Tiedtke</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-29T08:33:11+02:00">29. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/mises-spezial-142-geburtstag-ludwig-von-mises/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230920-thumbnail_youtube-520x360.png&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230920-thumbnail_youtube-520x360.png" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="MISES Spezial | 142. Geburtstag Ludwig von Mises" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 39.6px;"><a href="https://www.misesde.org/2023/09/mises-spezial-142-geburtstag-ludwig-von-mises/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">MISES Spezial | 142. Geburtstag Ludwig von Mises</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30941"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 63.45px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2017/05/Puster.jpg" srcset="https://www.misesde.org/wp-content/uploads/2017/05/Puster.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Rolf W. Puster</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-27T07:54:54+02:00">27. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/podcast-ludwig-von-mises-hat-so-tief-wie-kaum-jemand-vor-ihm-ueber-die-natur-der-freiheit-nachgedacht/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230906-thumb-web1-520x360.png&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230906-thumb-web1-520x360.png" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="PODCAST: „Ludwig von Mises hat so tief wie kaum jemand vor ihm über die Natur der Freiheit nachgedacht“" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/podcast-ludwig-von-mises-hat-so-tief-wie-kaum-jemand-vor-ihm-ueber-die-natur-der-freiheit-nachgedacht/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">PODCAST: „Ludwig von Mises hat so tief wie kaum jemand vor ihm über die Natur der Freiheit nachgedacht“</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30930"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 63.45px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2022/01/at2.jpg" srcset="https://www.misesde.org/wp-content/uploads/2022/01/at2.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Andreas Tögel</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-25T08:30:03+02:00">25. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/millionaerssteuer-und-gerechtigkeit/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230127-adobestock_19596834-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230127-adobestock_19596834-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Millionärssteuer und Gerechtigkeit" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/millionaerssteuer-und-gerechtigkeit/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Millionärssteuer und Gerechtigkeit</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30919"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 61.3833px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2021/11/sievert21-_-indischerseiltrick_ebook_2835px.jpeg" srcset="https://www.misesde.org/wp-content/uploads/2021/11/sievert21-_-indischerseiltrick_ebook_2835px.jpeg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Burkhard Sievert</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-22T09:18:14+02:00">22. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/wer-bestimmt-die-regeln/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230919-adobestock_98515510-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230919-adobestock_98515510-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Wer bestimmt die Regeln?" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/wer-bestimmt-die-regeln/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Wer bestimmt die Regeln?</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30914"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 61.3833px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2021/07/polleit_thorsten3.jpg" srcset="https://www.misesde.org/wp-content/uploads/2021/07/polleit_thorsten3.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Thorsten Polleit</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-20T07:52:48+02:00">20. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/podcast-die-falsche-priesterherrschaft-der-intellektuellen-und-die-macht-der-ideen/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230918-adobestock_622127990-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230918-adobestock_622127990-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="PODCAST: Die falsche Priesterherrschaft der Intellektuellen und die Macht der Ideen" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/podcast-die-falsche-priesterherrschaft-der-intellektuellen-und-die-macht-der-ideen/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">PODCAST: Die falsche Priesterherrschaft der Intellektuellen und die Macht der Ideen</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30903"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 55.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2021/09/fassnacht.png" srcset="https://www.misesde.org/wp-content/uploads/2021/09/fassnacht.png 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Rainer Fassnacht</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-18T07:54:12+02:00">18. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/was-hat-ein-belegtes-broetchen-mit-markt-und-freiheit-zu-tun/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230917-adobestock_54419654-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230917-adobestock_54419654-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Was hat ein belegtes Brötchen mit Markt und Freiheit zu tun?" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/was-hat-ein-belegtes-broetchen-mit-markt-und-freiheit-zu-tun/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Was hat ein belegtes Brötchen mit Markt und Freiheit zu tun?</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30874"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 55.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2021/12/kristoffer_hansen_2020.jpg" srcset="https://www.misesde.org/wp-content/uploads/2021/12/kristoffer_hansen_2020.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Kristoffer Mousten Hansen</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-15T09:47:15+02:00">15. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/will-die-fed-das-internationale-finanzsystem-retten-so-mag-es-vielleicht-aussehen/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230913-adobestock_611428443-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230913-adobestock_611428443-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Will die Fed das internationale Finanzsystem retten? So mag es vielleicht aussehen" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/will-die-fed-das-internationale-finanzsystem-retten-so-mag-es-vielleicht-aussehen/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Will die Fed das internationale Finanzsystem retten? So mag es vielleicht aussehen</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30856"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 46.2667px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2023/09/20230911-mises_karma.png" srcset="https://www.misesde.org/wp-content/uploads/2023/09/20230911-mises_karma.png 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Mises Karma</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-13T10:30:04+02:00">13. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/podcast-erkenntnistheoretische-kriegsfuehrung-mises-karma-live-event/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230911-youtube_cover-520x360.jpg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230911-youtube_cover-520x360.jpg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="PODCAST: Erkenntnistheoretische Kriegsführung | Mises Karma Live Event" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/podcast-erkenntnistheoretische-kriegsfuehrung-mises-karma-live-event/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">PODCAST: Erkenntnistheoretische Kriegsführung | Mises Karma Live Event</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30848"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 46.2667px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2022/03/20220316-david_duerr_1-scaled.jpg" srcset="https://www.misesde.org/wp-content/uploads/2022/03/20220316-david_duerr_1-scaled.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>David Dürr</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-11T08:31:04+02:00">11. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/175-jahre-schweizerische-eidgenossenschaft-warum-ludwig-von-mises-keine-freude-haette/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2019/10/alphorn_schweiz1-520x360.jpg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2019/10/alphorn_schweiz1-520x360.jpg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="175 Jahre Schweizerische Eidgenossenschaft. Warum Ludwig von Mises keine Freude hätte" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 79.2px;"><a href="https://www.misesde.org/2023/09/175-jahre-schweizerische-eidgenossenschaft-warum-ludwig-von-mises-keine-freude-haette/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">175 Jahre Schweizerische Eidgenossenschaft. Warum Ludwig von Mises keine Freude hätte</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30833"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 52.3px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2022/02/philipp_bagus.jpg" srcset="https://www.misesde.org/wp-content/uploads/2022/02/philipp_bagus.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Philipp Bagus</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-08T07:45:33+02:00">8. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/rechter-populismus-als-erfolgreiche-strategie-javier-milei/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230906-adobestock_101653989-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230906-adobestock_101653989-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Rechter Populismus als erfolgreiche Strategie. Javier Milei" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/rechter-populismus-als-erfolgreiche-strategie-javier-milei/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Rechter Populismus als erfolgreiche Strategie. Javier Milei</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30830"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 52.3px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2022/12/20221207-johanna_u_manuel.png" srcset="https://www.misesde.org/wp-content/uploads/2022/12/20221207-johanna_u_manuel.png 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Johanna &amp; Manuel</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-06T09:30:09+02:00">6. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/zwischen-schlager-und-autismus-mit-eigentuemlich-frei-mises-momente-10/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230905-mm10_thumbnail_landscape-520x360.png&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230905-mm10_thumbnail_landscape-520x360.png" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Zwischen Schlager und Autismus mit Eigentümlich Frei | Mises Momente #10" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/zwischen-schlager-und-autismus-mit-eigentuemlich-frei-mises-momente-10/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Zwischen Schlager und Autismus mit Eigentümlich Frei | Mises Momente #10</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30811"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 49.5833px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2023/09/20230902-newman-jonathan_2022.jpg" srcset="https://www.misesde.org/wp-content/uploads/2023/09/20230902-newman-jonathan_2022.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Jonathan Newman</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-04T07:56:53+02:00">4. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/hat-das-brettspiel-monopoly-etwas-mit-wirklicher-marktwirtschaft-zu-tun/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/09/20230903-adobestock_78823905-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/09/20230903-adobestock_78823905-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Hat das Brettspiel Monopoly etwas mit wirklicher Marktwirtschaft zu tun?" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/hat-das-brettspiel-monopoly-etwas-mit-wirklicher-marktwirtschaft-zu-tun/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Hat das Brettspiel Monopoly etwas mit wirklicher Marktwirtschaft zu tun?</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30792"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 49.5833px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg" srcset="https://www.misesde.org/wp-content/uploads/2011/04/mises_wappen1.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>LvMID</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-09-01T07:57:02+02:00">1. September 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/09/mises-monatsmagazin-die-beitraege-im-august-2023/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/03/20230328-adobestock_56479643-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/03/20230328-adobestock_56479643-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="MISES Monatsmagazin - Die Beiträge im August 2023" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/09/mises-monatsmagazin-die-beitraege-im-august-2023/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">MISES Monatsmagazin – Die Beiträge im August 2023</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30789"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 59.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2019/11/murphy_2017.jpg" srcset="https://www.misesde.org/wp-content/uploads/2019/11/murphy_2017.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Robert P. Murphy</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-08-30T07:59:09+02:00">30. August 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/08/podcast-klimawandel-die-falsche-behauptung-vom-97-prozent-konsens/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/08/20230828-adobestock_597784174-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/08/20230828-adobestock_597784174-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="PODCAST: Klimawandel: Die falsche Behauptung vom „97-Prozent-Konsens“" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/08/podcast-klimawandel-die-falsche-behauptung-vom-97-prozent-konsens/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">PODCAST: Klimawandel: Die falsche Behauptung vom „97-Prozent-Konsens“</a></h4></div></div></div></div>
       |<div class="col-md-6 col-sm-6 col-xs-12 pt-cv-content-item pt-cv-2-col" data-pid="30768"><div class="pt-cv-ifield"><div class="pt-cv-meta-fields" style="height: 59.85px;"><span class="author"><a rel="author" class="molongui-disabled-link"><img alt="" src="https://www.misesde.org/wp-content/uploads/2021/07/zt4.jpg" srcset="https://www.misesde.org/wp-content/uploads/2021/07/zt4.jpg 2x" class="avatar avatar-40 photo" height="40" width="40" loading="lazy" decoding="async"><span>Rainer Zitelmann</span></a></span><span class="entry-date"><span class="glyphicon glyphicon-calendar"></span> <time datetime="2023-08-28T08:45:03+02:00">28. August 2023</time></span></div>
       |<div class="pt-cv-hover-wrapper"><a href="https://www.misesde.org/2023/08/jung-rebellisch-kapitalistisch-kennen-sie-schon-die-anti-klima-kleber/" class="_self pt-cv-href-thumbnail pt-cv-thumb-left cvplbd cvp-responsive-image img-thumbnail" target="_self" data-iw="520" data-ih="360" style="background-image: url(&quot;https://www.misesde.org/wp-content/uploads/2023/08/20230823-image0-002-520x360.jpeg&quot;);"><img width="520" height="360" src="https://www.misesde.org/wp-content/uploads/2023/08/20230823-image0-002-520x360.jpeg" class="pt-cv-thumbnail img-thumbnail pull-left skip-lazy " alt="Jung, rebellisch, kapitalistisch: Kennen Sie schon die Anti-Klima-Kleber?" decoding="async" itemprop="image"></a><div class="pt-cv-mask"><h4 class="pt-cv-animation-left pt-cv-title" style="height: 59.4px;"><a href="https://www.misesde.org/2023/08/jung-rebellisch-kapitalistisch-kennen-sie-schon-die-anti-klima-kleber/" class="_self cvplbd" target="_self" data-iw="520" data-ih="360">Jung, rebellisch, kapitalistisch: Kennen Sie schon die Anti-Klima-Kleber?</a></h4></div></div></div></div></div></div>
       |""".stripMargin
  }
}
